[config]
schemaVersion = "0.0.1"

[package]
namespace = "LuaENVY"
name = "ENVY"
versionNumber = "1.2.0"
description = "A plugin to allow ReturnOfModding plugins greater control of their environment."
websiteUrl = "https://github.com/LuaENVY/ENVY"
containsNsfwContent = false

[package.dependencies]

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", "risk-of-rain-returns" ]

[publish.categories]
hades-ii = [ "libraries", "mods" ]
risk-of-rain-returns = [ "libraries", "mods" ]